// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     PluginSchemaRegistryJenny
//
// Run 'make gen-cue' from repository root to regenerate.

import (
	"github.com/grafana/kindsys"
	"github.com/grafana/grafana/packages/grafana-schema/src/common"
)

kindsys.Composable & kindsys.Composable & {
	maturity:        "experimental"
	name:            "TestData"+"DataQuery" & "TestData"+"DataQuery"
	schemaInterface: "DataQuery" & "DataQuery"
	lineage: {
		seqs: [{
			schemas: [{
				common.DataQuery
				alias?:       string
				scenarioId?:  #TestDataQueryType | *"random_walk"
				stringInput?: string
				stream?:      #StreamingQuery
				pulseWave?:   #PulseWaveQuery
				sim?:         #SimulationQuery
				csvWave?: [...#CSVWave]
				labels?:          string
				lines?:           >=-9223372036854775808 & <=9223372036854775807 & int
				levelColumn?:     bool
				channel?:         string
				nodes?:           #NodesQuery
				csvFileName?:     string
				csvContent?:      string
				rawFrameContent?: string
				seriesCount?:     >=-2147483648 & <=2147483647 & int
				usa?:             #USAQuery
				errorType?:       "server_panic" | "frontend_exception" | "frontend_observable"
				spanCount?:       >=-2147483648 & <=2147483647 & int
				points?: [...[...string | int & >=-9223372036854775808 & <=9223372036854775807]]
				#TestDataQueryType: "random_walk" | "slow_query" | "random_walk_with_error" | "random_walk_table" | "exponential_heatmap_bucket_data" | "linear_heatmap_bucket_data" | "no_data_points" | "datapoints_outside_range" | "csv_metric_values" | "predictable_pulse" | "predictable_csv_wave" | "streaming_client" | "simulation" | "usa" | "live" | "grafana_api" | "arrow" | "annotations" | "table_static" | "server_error_500" | "logs" | "node_graph" | "flame_graph" | "raw_frame" | "csv_file" | "csv_content" | "trace" | "manual_entry" | "variables-query" @cuetsy(kind="enum", memberNames="RandomWalk|SlowQuery|RandomWalkWithError|RandomWalkTable|ExponentialHeatmapBucketData|LinearHeatmapBucketData|NoDataPoints|DataPointsOutsideRange|CSVMetricValues|PredictablePulse|PredictableCSVWave|StreamingClient|Simulation|USA|Live|GrafanaAPI|Arrow|Annotations|TableStatic|ServerError500|Logs|NodeGraph|FlameGraph|RawFrame|CSVFile|CSVContent|Trace|ManualEntry|VariablesQuery")
				#StreamingQuery: {
					type:   "signal" | "logs" | "fetch"
					speed:  >=-2147483648 & <=2147483647 & int
					spread: >=-2147483648 & <=2147483647 & int
					noise:  >=-2147483648 & <=2147483647 & int
					bands?: >=-2147483648 & <=2147483647 & int
					url?:   string
				} @cuetsy(kind="interface")
				#PulseWaveQuery: {
					timeStep?: >=-9223372036854775808 & <=9223372036854775807 & int
					onCount?:  >=-9223372036854775808 & <=9223372036854775807 & int
					offCount?: >=-9223372036854775808 & <=9223372036854775807 & int
					onValue?:  >=-1.797693134862315708145274237317043567981e+308 & <=1.797693134862315708145274237317043567981e+308
					offValue?: >=-1.797693134862315708145274237317043567981e+308 & <=1.797693134862315708145274237317043567981e+308
				} @cuetsy(kind="interface")
				#SimulationQuery: {
					key: {
						type: string
						tick: >=-1.797693134862315708145274237317043567981e+308 & <=1.797693134862315708145274237317043567981e+308
						uid?: string
					}
					config?: {
						...
					}
					stream?: bool
					last?:   bool
				} @cuetsy(kind="interface")
				#NodesQuery: {
					type?:  "random" | "response" | "random edges"
					count?: >=-9223372036854775808 & <=9223372036854775807 & int
				} @cuetsy(kind="interface")
				#USAQuery: {
					mode?:   string
					period?: string
					fields?: [...string]
					states?: [...string]
				} @cuetsy(kind="interface")
				#CSVWave: {
					timeStep?:  >=-9223372036854775808 & <=9223372036854775807 & int
					name?:      string
					valuesCSV?: string
					labels?:    string
				} @cuetsy(kind="interface")

				// TODO: Should this live here given it's not used in the dataquery?
				#Scenario: {
					id:              string
					name:            string
					stringInput:     string
					description?:    string
					hideAliasField?: bool
				} @cuetsy(kind="interface")
			}]
		}]
		name: "TestData"+"DataQuery" & "TestData"+"DataQuery"
	}
}
